import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { db } from '../firebase';
import { doc, getDoc } from 'firebase/firestore';
import { AnalysisResult } from '../types';
import { handleFirestoreError, OperationType } from '../services/firestoreUtils';
import StepAnalysis from './StepAnalysis';
import Logo from './Logo';
import { Loader2, AlertTriangle, ArrowLeft } from 'lucide-react';

interface SharedResultPageProps {
  darkMode?: boolean;
}

const SharedResultPage: React.FC<SharedResultPageProps> = ({ darkMode = false }) => {
  const { id } = useParams<{ id: string }>();
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchSharedResult = async () => {
      if (!id) return;
      try {
        const docRef = doc(db, 'shared_links', id);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          const data = docSnap.data();
          // Check expiration
          if (data.expiresAt !== null && data.expiresAt < Date.now()) {
            setError('This shared link has expired.');
          } else {
            setResult(data.analysisData);
          }
        } else {
          setError('Shared result not found or has been deleted.');
        }
      } catch (err: any) {
        console.error("Error fetching shared result:", err);
        if (err.code === 'permission-denied') {
          handleFirestoreError(err, OperationType.GET, `shared_links/${id}`);
        } else {
          setError('Failed to load the shared result. Please try again later.');
        }
      } finally {
        setLoading(false);
      }
    };

    fetchSharedResult();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col items-center justify-center p-4">
        <Loader2 className="w-12 h-12 text-purple-600 animate-spin mb-4" />
        <p className="text-slate-600 dark:text-slate-400">Loading analysis...</p>
      </div>
    );
  }

  if (error || !result) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col items-center justify-center p-4">
        <div className="bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-xl max-w-md w-full text-center border border-slate-200 dark:border-slate-800">
          <AlertTriangle className="w-16 h-16 text-orange-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mb-2">Link Unavailable</h2>
          <p className="text-slate-600 dark:text-slate-400 mb-8">{error}</p>
          <Link 
            to="/"
            className="inline-flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white font-medium px-6 py-3 rounded-xl transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Go to SkillBridge
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col">
      <header className="bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 sticky top-0 z-40 transition-colors duration-300">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 sm:h-24 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link 
              to="/"
              className="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-500 dark:text-slate-400 transition-colors"
              title="Back to Home"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <Link to="/" className="flex items-center cursor-pointer group">
              <Logo darkMode={darkMode} size="md" />
            </Link>
          </div>
          <Link 
            to="/"
            className="text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-purple-600 dark:hover:text-purple-400 transition-colors"
          >
            Try SkillBridge
          </Link>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold text-slate-800 dark:text-white mb-2">Shared Analysis Result</h1>
          <p className="text-slate-600 dark:text-slate-400">
            This is a read-only view of a career readiness analysis generated by SkillBridge.
          </p>
        </div>

        {/* We reuse StepAnalysis but pass empty functions for actions that shouldn't work in read-only mode */}
        <div className="pointer-events-auto">
          <StepAnalysis 
            result={result}
            onReset={() => window.location.href = '/'}
            hasFeedback={true} // Hide feedback widget
            isSharedView={true}
          />
        </div>
      </main>
    </div>
  );
};

export default SharedResultPage;
